---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: cluster-admin
spec:
  # Ref: https://rook.io/docs/rook/v1.13/Storage-Configuration/Object-Storage-RGW/object-storage/
  store: ceph-objectstore
  displayName: Cluster Admin
