apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:cfBIQRW4IkJZ0+dvRDeDUen/yTShmqJLrBE4aNuDDrx5DzBJ,iv:Wv7rYOzQwADB+qCNdTHt26CAdIm/O6bhfRbyuJfjvU4=,tag:uKU3MrZ+xPvxdAd/2fm1Sw==,type:str]
    credentials.json: ENC[AES256_GCM,data:s8kV2Hnu3kFsk/VaCTyvXI5dIir9Hx6qmyR+9GWo2NgAJCrjp1woWVSQm9OQ5R2UhY4LZ13w1/QAMwpYYUo71PAtPy3MGPVLHpUCoyBz6A+kgpWkXS+O8wWRluYcn7sJw21DkC/HBRh8UQsDKs9Vz+vTkqTe0aIymD13DMzSRBbFUO8qyDgLkyaJY3L79WhG8GEUA+8CHUpc3pA9vNzna+N8a+8JjkSMObBJFcAjlg==,iv:SDUDiX3NWSZeurovO4HnUSy3ROAdZKpZ49YM/JAJIx8=,tag:UC7ZGG8Mk7BSOsMGoIFjIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1palcdmhvfs9p9ymmh62n2mva95hmyxpp3d4kfj5ven0pujg0cpqsdjmram
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZmlpakVpcG9DeGJPbC81
            cERlb3hsdjJJUUl0S0RnK25MOCtwOWlQbFJ3CldiMFIyVE5ydXVrNk1YRGwxcTAy
            N3I3cEVwc2I1bXM1a3lMbzNsYTNrNmsKLS0tIDFJMy9oamtaSmFjbnhJcDhrMGlE
            RENhcnBjOWxrV1FJSE5oSlNIc1NSYTgKGWT52oD7BsOpEh2pI9O0SPoRPROMrSSP
            6p8Xymq7QZoLFDLK0/mldCnT/2+oVMo415jqsIHeSmny63aR6qNlxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T08:55:41Z"
    mac: ENC[AES256_GCM,data:44mQ8XlOY2t84Tb8xkUQQWUGE2B6GOPmOJkY4Olald5xQqf0w6Tta11/aZeRaqVr90vxLTvVhmRprdF0c+j5RI6hsU4yAxiIOJ2phCZbe9t5Q+1x/kmgMcJ6pGRX9MeNxZMtrR4AyEg/d3GQsNTiiJ+pvTZYXj19/uP8Zy5numI=,iv:z1x/LySKaliMo/PRI50ByGOdFwvsHyA8SJRoKnVMJyU=,tag:szGQir6Res5904v7MjAPMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
