# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:qejAIfdSPg6JCak48HGj6Suv6ONdimR7Gt5pGUml/N25uzh8A/tXQ3mNsDbhk85VcB19n5LSojnfzWGVu1HurhofLv7e6M+xiI+4MHyMFGDrN9X+Y4P92xd+xeAdohJJaSv+ESmZeTYHznsAZZOMuWhKVI2Na+q7jvpu7AHzKD0uh2MlGuDk1vonl8V8TA2DDv+awqdo4FnOITJM8fokJmuRPUOCQTAm2nCzJVb50BEnPeR4fnlpFKr2oMVjeg/mxGpx2yq+XHaK5nd3rFjVUWYhj42MNmF5MTJWl4a+nxKGfPJAxJp4DXcNbDDfoeboXQyD4+XVDfPD6m9VprJ5zJXhZdOgtAij0QRYBndihQqfyiMfbAmLbvGTeyFYtCwfyZqa3zi+pF6VFCwB6+7VjGpnSdwyPhBnXsifwqZfsuV49NxGYuc/qckSoIx/DzY8h6S3AMgxJVxqGxiuq2YC2OkfMQP5MTjRfrTNT9XECWPjqD5zcuOXKZOlBfI/2vWlqI3+TlVsoZWTQ/qJ61N8zvIgSlE88iLDmL+eYlaBRleOkFBRqCjEJwaI6vCCrI+AhFulEgYdQkC8NfMBLvxCUzCnnfmXi1SRQfGglA0Oe9gqF0HfeW4kpH7cGXFhOg1PLUdlizK9LEjmmwPid09mDTnfE9uv1gqaAoy1fdjLNv0aBRvcYKvFfOx4XpT6gOWQC/zEjryOGLD5A22zIYdNaCL3fBHen6Ak0uLbfoCiOIluD0WixSORmX604hcrbKL7hXB4e+zhJdL93upUo0tKgChS99LD7rL6ajAvOREt/Hp1fREp5rvY/zLnZKimO42m8/r15RKUq6hFRNySVNidqdRCQiX/ZvaO2g+gRx/9YUvGgrLXhqLexJc/zaZLXFDkIz0d7UudSRxjw0QEYCTLV40guCpTdptw0fnoJnVpvAAap393q20hDZr9z1gWkZKGn7z/ohMrxzwmE4LP+gnSkqbiS4+j5/wbVA59AAjplTNXdEgWuxKAmT7fd1IYvacJ0OvzbyTvVP5v0e4Jlj+6EMSrcfn/6i9RCgYYk9UU3jOw6MMR18dTs/UUQADyo5n/DH7biU7sMxo9gh01qg+QqQjudYgA86HSqOKHbCXDJrZi9CHQaLTQESfAp4C8S74Ioz1kgwB0/lEi/qdWmEPkxIjsUAiAL+2r00mQpmLM8SU3wcPRB+T9oEz0+/4vofSxxkdwAWN7TdsS3iT17m0aN0y4hA5TRr/v+oiR+gsHs/jqd2PqvduZs52saVtNYWpxisyOR7/q4WpM97mz9Zf991tqTYJ182wrzLC20GvPVjh/wBeW8wG5r67UK19MFjQnbl2qsrTG3l38vLLigu7tsN5fT/pIgDnTyIGvnsYI5VKHLYoKUFXHF0u4liH0U+R27UTtaWmMjlP+XYNF2R9Ra20r6a6BrjxbO7MR6DCQMA3MCgrIQ1CWypfDZEajL/2PrT9kCBnRT+7WPSTfK5Yk6Xghc00aibTWEOf/M8X+NmFLRwliz6YKUA8f/8wjo5TSHngU7MXVAsnobPb8s9ejP5SdPoL2s3bRE8xXIiMor4u9jvOBML/UctL/vYocX3+STHK3Gln3kWYXIjTh+t5PrjWNfvGEhDWGYrOcqmBOw4Pv1g+D6C4OgR951QcSiWqgRVv8VNn3g5YCRXfUWdaOmswsXh4A0P7v5UBCUineJQFluG034Pv0RwEnTJ6iSucUI3za54J1jmlpmzfeBfG3E98DDX9/nSvRoN6U7+rSXic103EXaRdxxK52yktkp7xQiFngBfip73U3FW48ehuPDE4CBpH0b5BzcB//PQBul1KkA469vZX8ahiNbVxja41K8ngqqMMcT+7lWZ2M0xd7utcp+BGyflDfiFXGMBj4sqkYpPhmi4sUY3d4Jq8kRY0WuUJowT2SpgcQyMyV,iv:7t1m0RiH9dWb8NGBRFo+WgDppoaQUX0ZomyiMO/VZek=,tag:G5sNFQR2dGSicDOGy5NPkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MEIrcGlkM0VTMVNod1NS
            aTNvekdCQ0NGRDFMV0FVLzlaZFA4TUtJMWkwCkdPaVVJM1JTUVBLTldWTXNZQ3Nw
            SGJ3eFdMcElhWWR4NFp5NXRObG9xZ1kKLS0tIGt3NCtaZ0pOeElDZXVFZHp0V0ty
            dDJsNnRHcVQ5WE0yMDJXWGh0Z1dzbmsKOhvfigtuCMigBn7Wi3IS1h6PedZDBWat
            yIcmxjRwWbIAllW44QnsjFGWCIAp/y3eF0G5WkmrGECWjF9HcYJ7EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T07:51:18Z"
    mac: ENC[AES256_GCM,data:vFagOwwtkrnugCC1c9Yae8t1PmIHFoil5TTzoybsYSdXeaYG+ZQ1tH/+AKDsaXzzuvqIfopfOsgiCsWfwvtV0oBqCoEHzkhwQsj88gDc/KF4wmlrLtaUxD/5iu+LHeCSyfRh6emkNAl00dZOmOPe1RbFpeOHmjbmdIrvkGuUwhI=,iv:ttS0rNTeLt33X1wyciqtIXJgrN/D2bGOFtYIAlR47L0=,tag:6FqDm5uU4xxXcoji1SkTJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:snqGGEwGGG6DKhePsX0Yb0iXk5HEC3NME6lxNtpeJ1dz40+N/ggsMfP62RxBFH7FfV9Ly1M8cSnygLNa8P+U0KlsBcL2Ak9lAp+FHcNMNDfEVYQXM/LwA8Om6ln+Dh9ne27GRAFae75yO2i7p/T8vzBqJ8d8phKeXphP8pJICza4S9QEi63WIvFXrbqefTj+M0qK4NtHM7TfpQrrU6wl+9WOUQ0gwfLOIPOS6T7ZVB9hJhDMN2PfhQxGQ009XziZHtdUN1CZtfahitfjThBZwObNJG3VaIXGlGtUg9dANjFiCmrYHM8JONWKOD/f7k646nU3RuduQCOKY9dRw/A1ktbyjFzb2JPr+2zaa8kgSu0o8hChBESCn+7cCMslPHRfJ7ud4gJxU/O+dsAXK/kE+dWGCQ29Kx4NeeiYRbqoQ5WB7+fGIPVBs+h0dvvr0igKMxSnlH68S0Ouehr6xYP9G4Yn44a70eIh7hRkdFD/Qf/4MjuXQEZnQwvpV6+spZC5+eoX7aY/lIRERvFoU1rteoUuk9zdyl9JitZovlcVQeoCeQP2eFd+ozD5cFbKVmXqco2Gm4Ee0KJIuUbBqspC35qHdof4MPNeTZ0hE7loV00BPM2g7RIUmJLJKShk3QFXkSJC/ga9axQd3XqGM1nVrB67d6hXc/L6p5B4XbQSQ+7j/euZ0np4OjoJmAzYp/MUt2dtm7pY/0KcjVDFsy8oEbHHenX3Iej25f23BpiGHwoiACJzkQIBeuTOMfneZgcJqRYKAFAvbPwwtos0IHMVgfvRDhMhrDIu4TkQ33C3cLe5hRuY/OAYJ8OlTRqAnZo2gh7ySZ4ThvF2i/QNwLqkUcyy,iv:mRR0dku8Lz5zG4CPTTUEeM+HUynNYJ4FOcI3jfxO86g=,tag:TxXlXQDLw9pOBBMAwa51hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MEIrcGlkM0VTMVNod1NS
            aTNvekdCQ0NGRDFMV0FVLzlaZFA4TUtJMWkwCkdPaVVJM1JTUVBLTldWTXNZQ3Nw
            SGJ3eFdMcElhWWR4NFp5NXRObG9xZ1kKLS0tIGt3NCtaZ0pOeElDZXVFZHp0V0ty
            dDJsNnRHcVQ5WE0yMDJXWGh0Z1dzbmsKOhvfigtuCMigBn7Wi3IS1h6PedZDBWat
            yIcmxjRwWbIAllW44QnsjFGWCIAp/y3eF0G5WkmrGECWjF9HcYJ7EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T07:51:18Z"
    mac: ENC[AES256_GCM,data:vFagOwwtkrnugCC1c9Yae8t1PmIHFoil5TTzoybsYSdXeaYG+ZQ1tH/+AKDsaXzzuvqIfopfOsgiCsWfwvtV0oBqCoEHzkhwQsj88gDc/KF4wmlrLtaUxD/5iu+LHeCSyfRh6emkNAl00dZOmOPe1RbFpeOHmjbmdIrvkGuUwhI=,iv:ttS0rNTeLt33X1wyciqtIXJgrN/D2bGOFtYIAlR47L0=,tag:6FqDm5uU4xxXcoji1SkTJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
