# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:5A9gEK5CI3iY6I6805Omb3/28cq99WSOefqxXc1Bgh7jGgHfqY7BYmFGNgbqy0TLr6ziIrqYEyIHf3i6wCalfb44GO0CxYGU+T0V7bsjk+6BEjJ1QFg3aPKrQXdFz+9LK9HL+RGpI3Ecmw05y+ccjuIZs7plJ0YymOT074raH7jY0fnfTmjjIx+mNU0K/Q==,iv:43UsOlREM5h5jz+QsBAcWyz3eZGP3b/cNYbr9lsu2r4=,tag:agVH6+tuMfTWuNwtwapqlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNm5zVjVTVUhuNU9KRlBC
            enU4SVdERmxXRThONXFPRWRtNlllL0hOdkVzCmhsVkZqZWNYd2svZTFXUUFMRm5G
            MFNpMnduRDhFWGdWZmtTVWFQTkp5eEEKLS0tIGZuR2hvTmVtTm9jV0RDRUhidHRJ
            SE5tdnBUcUlRTzd2dDRJc09zR28rcWsKM3xgJoYwRJd703irtubczsrbgZvwK1lo
            wpvqcYTYGusxv8ox0SQHKQfW2b0g68my7vclpNwBLorK9XKkMTLtrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T05:55:16Z"
    mac: ENC[AES256_GCM,data:IfaCdYzlNjFiroCgYbwy8QNL68FoynG+Qrzz5FHYljnDY+NbmJBtVuD++DS6NMOO+r0+2yrFpbiyQdLP1clFBzt41kBGrkJaMmiUcuzxqTw5kcwe1mutqef9GXQ9I3y6HlmflSPgceAMkKxTCjVGkbHlXaqjxtxXcQCcY5Cr2T8=,iv:GIS3hx5QM1PdQSntdXWtxBXqXgMihDgoCEv/XOULe8c=,tag:3FTeuLDUZeftIWJVHPAAkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:SDVUNkZFS5WgePNXFfoeCcXmDIyi1MjXIr6bFvoMDwwHsu0fcpJ18tC0xFUgwSaLixr0z17at1XAMTQqwjqXFf7PgMShBdaslpqhPR5CT6aGYLpO88X4B7IOqkYSTDhrSMx/aiFSEq3D1nrbGCktQgvclZYrsw1NhIT8CwwYBiUzOVmOgqjhvzQMV4zxJrHRqwG5XZVQvf2xss7i1sznGl0Jng==,iv:Eo6267DhIyuQPS6KM+pv83MH3XfX+H3df1YC5Pgyzq8=,tag:RfVDx91Z7gyShfLvbv5kCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNm5zVjVTVUhuNU9KRlBC
            enU4SVdERmxXRThONXFPRWRtNlllL0hOdkVzCmhsVkZqZWNYd2svZTFXUUFMRm5G
            MFNpMnduRDhFWGdWZmtTVWFQTkp5eEEKLS0tIGZuR2hvTmVtTm9jV0RDRUhidHRJ
            SE5tdnBUcUlRTzd2dDRJc09zR28rcWsKM3xgJoYwRJd703irtubczsrbgZvwK1lo
            wpvqcYTYGusxv8ox0SQHKQfW2b0g68my7vclpNwBLorK9XKkMTLtrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T05:55:16Z"
    mac: ENC[AES256_GCM,data:IfaCdYzlNjFiroCgYbwy8QNL68FoynG+Qrzz5FHYljnDY+NbmJBtVuD++DS6NMOO+r0+2yrFpbiyQdLP1clFBzt41kBGrkJaMmiUcuzxqTw5kcwe1mutqef9GXQ9I3y6HlmflSPgceAMkKxTCjVGkbHlXaqjxtxXcQCcY5Cr2T8=,iv:GIS3hx5QM1PdQSntdXWtxBXqXgMihDgoCEv/XOULe8c=,tag:3FTeuLDUZeftIWJVHPAAkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
