apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:lUiZ+Tp7I+c1rOifI9A7a7AEn7bkP5a04qJ+XKsKJr9BFFn+LGShEl3I374fkocxz5gFrpG2H0iFwD0wdgE5dgtSGPb9cLzbNGBf5gl6fnP9zyhl0Io64lnJR9gLsg==,iv:l7/R1ZxYCOQA/OSqLCQy9Ej8pg19Fpd4+6Q+dLX8GX4=,tag:vl6bcVFFl0eWZJGogxyKXw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4MbSjSxtnoV5aAE=,iv:UWWK9F7ji/bb6bV0ZCM5ZkNHKOScP1P99pTdCyCDB1U=,tag:7EogBjcyfe9GiaDIM6QpYA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GdczkmK75Ee49U20MVQ3Ow==,iv:CJMuLa3N9pQvTdMtuiMHbIiAwtKzwhdqkCCfng2OUns=,tag:Le97SVbMftvcouTtkOL6Jw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Tua8YOH0kNVrNGgOV54rEjbOTy8kYogmkjoYJJ2mJc/kpPaS,iv:ns0WeId6mZxQoyK+wU3THKD4PHvveSmDRnYbcAxkOh4=,tag:EGfujjrh8ZOKKMMuGiGcjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1palcdmhvfs9p9ymmh62n2mva95hmyxpp3d4kfj5ven0pujg0cpqsdjmram
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYi9JeTBRS2UrN1B4cjVs
            b3NqSVZBNGMwNWNPMDJuTkZ6b0RGTUY3T253Ckk5SjBrWXRabWY4V0RzTlFOSnZx
            ZTQ4MjAweEd2cWtseU5UejdqeG9JSDQKLS0tIGNVZjNSMThyMU9EZlk4OUdCNWRU
            MDJPSGx2bWtYNkpQWloyY2FoSi9UV1UKl6vRlOQNmKEFkqOsDktTPTi55Ic+Vr89
            LD6AY7TVtwtzIHJPAd5uxlys/IMa8sq3J5GW5IxfKNkfNmWdZLhfZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T08:34:49Z"
    mac: ENC[AES256_GCM,data:d8UfRHFw/eq8iw5R39gRny6UUkjmQYBz7Pt+Bst+Mcxn3KSLH1yz/RdrLIsz7roBwiAWELJMXjs7exOlJEmd1TmK0wluv8lPNizLxy9INuImO4+18JzRQAZj2SmotNHpCJay38wN8CK1tKw3bdJMZaYvDOvlO6E4VWfD7gNUPb4=,iv:q8Bxz02Xz5grsfK05/BVVRccam6t/x8rLmUOyAs/cy8=,tag:I3rANHsEV1oh0tTPNPwOWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
