apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:AzLO4BwKNtciYuv/plrxgvki6VGKRSjkZEWmpR/NuY4=,iv:E+zkClhnNSOXfWhp7mku76S0o6BhRIFDaIV+qxaImwI=,tag:xipGy3EvcLJjCkPNt/1EHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1palcdmhvfs9p9ymmh62n2mva95hmyxpp3d4kfj5ven0pujg0cpqsdjmram
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM0Y3eVhsUXoxMEFKdjZx
            MzNvdXlmVkNBRzV3SnY3MW1yQzdDTDgwWENrCktFZUdMTDc0aE5STUZKNXcwVGJR
            STNMcVdDd0R4QVhVdWcvTzZHeDZ3MWcKLS0tIG1CaEtOSjZoZFVmYlNCVElCU2pj
            QjVxZTRMTHVKS2FiUmZYRy9seVBoUk0KVZHq3nedpx+Zf2Ektm2IXvtGCCUmdMdP
            nKfgghaC3gY76b2SDhc2AGKSHnLPqSgqarlXnWl4oW1fJBWP22xfwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T08:34:49Z"
    mac: ENC[AES256_GCM,data:He0/zmcbL79v27Jw5l0BwefDG1BTzqxrrpkAX4RbmIP9/WKxfztZeMKgdiaiMEZWfA4EabKRaHr6ca6FxgHIpV7Cfh/+8NCeo0jWvAlSEcV7fEKwcIC7JCqkZSrUB3RGtPHgimcPIspcAYIxUxF+k0aERhxXszcU+ModXsTCClY=,iv:R+zYbZL4diaU7dO/gLvIR0YsxiUICAmOtvcjEhSE5Eg=,tag:feT/B/77+eu1k/MvrciLbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
