apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:52kadleJwmYwLSjgSziviD3zj+4iYaavYdn7SZQHreA=,iv:oQEs58OCriCzA2pT7TbXkmaxT3GWvOpaa5ehLffednc=,tag:M8gpBpRIsFTfsF5BU4yfOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1palcdmhvfs9p9ymmh62n2mva95hmyxpp3d4kfj5ven0pujg0cpqsdjmram
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VjE0dzA3N083SmJaQXdt
            WFFOZENId1hXTks3QWJ4ZUV3SjNXYTRHUkJnCjNrY0cxYTdNMVlPV1JmejZZVEpL
            RWNpRFp0WVlsdnVXa2FlNjEwSHl0QjAKLS0tIE9GRUVhQ3JGRkwraXpiVzFjUGx4
            a2ZETFUyL3pZMkIxMlU5ZVl3K1U3SVEKJ08Dgm+N/NnGLLk8glvh82ngbtUa3UjD
            5zGx7uOrOavwyfxupMNzF4G+asCWOFGo39v3/nvXCXXgphHwqQ3OUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T08:55:41Z"
    mac: ENC[AES256_GCM,data:dRF3yvB/D3LcZkxLLVDPgfEmqn1nfsPl3AfMxfsSpRmTWcaXWMfw7Nn3OIRfG5DD0ytV4evov6JkioiIs7e0LRCRxkv6/RPmELleiZH+MfQOFyO2OUcJaZ3IsPU8HnAA0cWOgSlfIjS267irBnqV6Yg1Rm7Waqnx1AyQ8KbK/Mo=,iv:quUlxagfBQ7eJoosXR+8HDvQyIBpYrBpNuUzmF6YPek=,tag:P6YNX9ebGASq0vM9Zx1woQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
