apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:J6h0dH8XG4qk7CCE+5idN05p9nHL/ne9Mv8h8Zgsehc=,iv:jl2B7gR2C8Sw9yyHF/F1IiwJfNw/2MtOqhkb546CDro=,tag:Sl87NbRNh4JA8E3VtZJF6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1palcdmhvfs9p9ymmh62n2mva95hmyxpp3d4kfj5ven0pujg0cpqsdjmram
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcUkzNGdLdHdWQnp0SXpj
            T3FTYmFLdnc5a2ZtK2orbVVNdGtvWXh0V1cwCnJyWmFIMDMyK0tCa25vWDlDZmFi
            OHIvZS9HTXFOb200LzdrdDVUV3Vlb2MKLS0tIGJtWmZTYnZrNVlQQmtUcVAzS2pE
            b0hLMlpvcmgyalN2eUdOMG40R1RZa0UKCaw9GWRnhGbdI8G533S679t7TnmW7tE5
            yppV/fOExfrOLnqNkJopBkSCVLmgjNcMccnNGSdWrTnC4cC5mdAfTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T01:45:09Z"
    mac: ENC[AES256_GCM,data:IiD1Ql9JZzU3w36pnzQpaixMEsPxAbn/d9iPX7I5K6EgP1pG46aEXWdCHnyvhb/nWB26piQ3GZrGwIbJKskv6qhK2L6hScm4yPwsTabFr8njn0ZAf6kRy9cTbK6jtR51OBJ9Xv727NEErWj2Yxrv4wyzXoD35XS0ms6N7VGv/ow=,iv:mFH0Mo4Ob0YUYciaNJaifrT5yWBo8IYkVrS1tD3s3/I=,tag:B01tcoJmQumCtaRKFtqLaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
